#language: python
#
#python:
#  - "3.6"
#
#services:
#  - docker
#
#before_install:
#  - docker build -t containerimage .
#
#
#script:
#  - docker run --name testcontainer --rm containerimage nvidia-smi && pytest

language: python
python:
  - "3.6"
install:
  - wget https://repo.continuum.io/archive/Anaconda3-5.2.0-Linux-x86_64.sh
  - bash Anaconda3-5.2.0-Linux-x86_64.sh -b -p $HOME/anaconda3 > /dev/null 2>&1
  - export PATH="$HOME/anaconda3/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - pip install -e .
  - pip install pytest-xdist
script:
  - python -m pytest -n 10
